### ISSUE TITLE
Table IBISSTORE not available when default database has been changed

### ISSUE THREAD

**Issue by mhdirkse** [frankframework/frankframework#7289]
### Current Behavior

I am starting the FF! using docker compose. I have a docker-compose.yml that contains:

```
    environment:
      instance.name: frank-docker-example
      dtap.stage: LOC
      configurations.directory.autoLoad: true
      configurations.names: ""
      management.gateway.inbound.class: "org.frankframework.management.gateway.HazelcastInboundGateway"
      jdbc.datasource.default: "jdbc/db-loc"
      jdbc.migrator.active: true
```

I do not have table IBISSTORE: querying that table in the Frank!Console gives an error. I do see that the Liquibase script that creates the table did execute:

```
v530-frank-docker-example-1  | 08-Aug-2024 15:55:15.166 INFO [main] org.frankframework.credentialprovider.CredentialFactory.tryFactory installed CredentialFactory [org.frankframework.credentialprovider.FileSystemCredentialFactory]
v530-frank-docker-example-1  | 2024-08-08 15:55:15,488 - Created IbisApplicationContext [frank-docker-example] in 2261 ms
v530-frank-docker-example-1  | Running Changeset: IAF_DatabaseChangelog.xml::IAF_Util:1::Niels Meijer
v530-frank-docker-example-1  | Running Changeset: IAF_DatabaseChangelog.xml::IAF_Util:1b::Gerrit van Brakel
v530-frank-docker-example-1  | Running Changeset: IAF_DatabaseChangelog.xml::IAF_Util:2::Niels Meijer
v530-frank-docker-example-1  | Running Changeset: IAF_DatabaseChangelog.xml::IAF_Util:3::Niels Meijer
v530-frank-docker-example-1  | Running Changeset: IAF_DatabaseChangelog.xml::IAF_Util:4::Niels Meijer
v530-frank-docker-example-1  | Running Changeset: IAF_DatabaseChangelog.xml::IAF_Util:5::Niels Meijer
v530-frank-docker-example-1  | Running Changeset: IAF_DatabaseChangelog.xml::IAF_Util:6::Niels Meijer
v530-frank-docker-example-1  | Running Changeset: IAF_DatabaseChangelog.xml::IAF_Util:7::Ali Sihab Akcan
v530-frank-docker-example-1  | Running Changeset: IAF_DatabaseChangelog.xml::FF_Util:8::Yannick van Leeuwen
v530-frank-docker-example-1  | Liquibase: Update has been successful. Rows affected: 9
v530-frank-docker-example-1  | Successfully tagged '@jdbc:h2:mem:test'
v530-frank-docker-example-1  | 2024-08-08 15:55:18,028 - Configuration [IAF_Util] [null] startup in 2427 ms
v530-frank-docker-example-1  | 2024-08-08 15:55:18,294 - Configuration [my-config] [null] startup in 176 ms
v530-frank-docker-example-1  | DispatcherManagerImpl DEBUG java.lang.ClassNotFoundException when trying to load DispatcherManager using ClassLoader [jdk.internal.loader.ClassLoaders$PlatformClassLoader] that is parent of [jdk.internal.loader.ClassLoaders$AppClassLoader]: nl.nn.adapterframework.dispatcher.DispatcherManagerImpl
```

If I go to the Frank!Console JDBC | Browse tables, my changed database name db-loc is selected. In the dropdown below that, a possible value is IBISSTORE. But if I click the button to see the contents, an SQL query is generated that does not execute on the database:

![image](https://github.com/user-attachments/assets/9a3a246a-b918-45ea-b454-9603a7d0f37a)

### Expected Behavior

Table IBISSTORE should be created in the alternative database.

### Environment Information

**FF! 8.2.0-20240711.042331**: frank-docker-example 
Running on **6a3b403ec8bc** using **Apache Tomcat/10.1.24**
Java Version: **OpenJDK Runtime Environment (17.0.11+9)**
Heap size: **123.1 MiB**, total JVM memory: **392.0 MiB**
Free memory: **268.9 MiB**, max memory: **2.0 GiB**
Free disk space: **40.1 GiB**, total disk space: **58.4 GiB**

### Anything else?

The full code I am working with is in https://github.com/frankframework/frank-manual/tree/docker-devel-and-prod/srcSteps/Frank2DockerDevel/v530 for the time being. I want to change the default database name because the available database can be different during the life cycle of the application. If these databases have more differences than the hostname, you need different resources in resources.yml and therefore there are different JNDI names.

**Comment by mhdirkse** [comment]
I tested that Frank2Example3 in the Frank!Runner still produces table IBISSTORE as expected.

**Comment by thomaspj10** [comment]
Changing the database from H2 to MySQL does yield the correct result. This problem might be just with H2.

As a side note, there seems to be some issues with the syntax of the SQL query used in the JDBC > Browse tables tab. The syntax of the generated SQL is not valid for MySQL:
```sql
SELECT * FROM (
    SELECT ROW_NUMBER() OVER (
        ORDER BY (SELECT 1)
    ) AS rnum, * FROM IBISLOCK
) AS x WHERE x.rnum BETWEEN 1 AND 100

```

**Comment by mhdirkse** [comment]
My problem has not been solved. I am using the docker image of the FF! and I have no control over the database URL.

**Comment by nielsm5** [comment]
The database URL in the example project looks fine to me, see: [example/resources.yml](https://github.com/frankframework/frankframework/blob/master/example/src/main/resources/resources.yml).

The compose file you provided is incomplete. Could you provide the image you're attempting to run?

**Comment by mhdirkse** [comment]
Here is my full `docker-compose.yml` file:

```
services:
  frank-docker-example:
    image: frankframework/frankframework:8.3.0-SNAPSHOT
    ports:
      - 8080:8080
    volumes: &frank-volumes
      - ./configurations:/opt/frank/configurations
    environment:
      instance.name: frank-docker-example
      dtap.stage: LOC
      configurations.directory.autoLoad: true
      configurations.names: ""
      management.gateway.inbound.class: "org.frankframework.management.gateway.HazelcastInboundGateway"
      jdbc.datasource.default: "jdbc/db-loc"
      jdbc.migrator.active: true
  frank-flow:
    image: frankframework/frank-flow
    ports:
      - "8081:8080"
    volumes: *frank-volumes
```

**Comment by mhdirkse** [comment]
I was wrong with my recent comments because I do have control over the database URL. It is in `resources.yml`. I will test whether the analysis given above is helpful now.

**Comment by mhdirkse** [comment]
My problem is solved by updating my `resources.yml` to the following:

```
jdbc:
  - name: "db-loc"
    type: "org.h2.jdbcx.JdbcDataSource"
    url: "jdbc:h2:mem:h2;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;"
```
