### ISSUE TITLE
JMS implementation seems incompatible with RabbitMQ JMS

### ISSUE THREAD

**Issue by tommy2d** [frankframework/frankframework#8096]
### Current Behavior

When using the JMS provider for rabbitMQ, java.lang.UnsupportedOperationException is thrown when attempting to send messages to queues or topics.  

This seems to be caused by the rabbitMQ JMS that is missing method implementations that the JMSFacade and JMSPoolSession are expecting, such as setMessageListener() in RMQSession.java:

`
public void setMessageListener(MessageListener listener) throws JMSException {
    // not implemented
    throw new UnsupportedOperationException();
}
`
The above might be caused by RMQ JMS not supporting server side sessions (https://rabbitmq.github.io/rabbitmq-jms-client/2.x/stable/htmlsingle/index.html, limitations) but I'm not sure.

Stack trace is attached.
[ff stacktrace.txt](https://github.com/user-attachments/files/18137409/ff.stacktrace.txt)

### Expected Behavior

Successfully send messages to AMQP queues or topics on rabbitMQ.

### Environment Information

- ff 9.0 latest
- amqp-client-5.23.0.jar
- rabbitmq-jms-3.4.0.jar

### Steps To Reproduce

Run framework with attached config, setup resources.yml:

```
  - name: "rabbitmq"
    type: "com.rabbitmq.jms.admin.RMQConnectionFactory"
    url: "amqp://host.docker.internal:5672/"
    properties:
      virtualHost: "/"
      host: "host.docker.internal"
      username: "admin"
      password: "password"
```

Open http://localhost/api/test/ in your browser, receive the attached stack trace.

### Configuration

```xml
<Configuration name="Config">
	<JmsRealms>
		<jmsRealm realmName="jms" queueConnectionFactoryName="jms/rabbitmq" topicConnectionFactoryName="jms/rabbitmq"/>
	</JmsRealms>

    <Adapter name="Adapter">
        <Receiver name="ApiReceiver">
            <!-- This listener is used when the API is called as specified in OpenAPI 3.0 at the Webservices page -->
            <ApiListener
                name="ApiReceiverListener"
                uriPattern="test"
            />
        </Receiver>
        <Pipeline>
            <EchoPipe name="OutputNoOpenZismuts" getInputFromFixedValue="blaat">
            </EchoPipe>

            <SenderPipe name="event-payload-sender">
   
                <JmsSender transacted="false" synchronous="true" jmsRealm="jms" deliveryMode="PERSISTENT" messageClass="TEXT" lookupDestination="false" destinationParam="destination" jndiProperties="jndi.properties" acknowledgeMode="auto" destinationType="QUEUE">

                    <Param name="destination" value="zismut" />
                </JmsSender>
            </SenderPipe>
        </Pipeline>
    </Adapter>
</Configuration>
```

**Comment by tommy2d** [comment]
UPDATE:

When I remove the explicit UnsupportedOperationException() throws from the rabbitmq JMS package, I do get valid messages in my queue, but the frank!framework still throws because it does not get valid responses:

```
rg.frankframework.core.ListenerException: Pipe [event-payload-sender] caught timeout-exception: did not receive reply on [RMQDestination{destinationName='jms-temp-queue-649e8867-238d-4b38-862b-7a0165d1144f', queue(temporary)', amqpExchangeName='jms.temp.queues', amqpRoutingKey='jms-temp-queue-649e8867-238d-4b38-862b-7a0165d1144f', amqpQueueName='jms-temp-queue-649e8867-238d-4b38-862b-7a0165d1144f'}] requestMsgId [ID:a07c1c08-d2a8-4578-ba8d-7cc0da0c721b] replyCorrelationId [null] within [5000] ms
	at org.frankframework.core.Adapter.processMessageWithExceptions(Adapter.java:621) ~[frankframework-core-9.0.0-20241213.042326.jar:9.0.0-20241213.042326]
	at org.frankframework.receivers.Receiver.processMessageInAdapter(Receiver.java:1286) ~[frankframework-core-9.0.0-20241213.042326.jar:9.0.0-20241213.042326]
	at org.frankframework.receivers.Receiver.processRequest(Receiver.java:1060) ~[frankframework-core-9.0.0-20241213.042326.jar:9.0.0-20241213.042326]
	at org.frankframework.http.PushingListenerAdapter.processRequest(PushingListenerAdapter.java:106) ~[frankframework-core-9.0.0-20241213.042326.jar:9.0.0-20241213.042326]
```

**Comment by thomaspj10** [comment]
`RMQSession#setMessageListener`, the problem function, is actually not called by us, but by `org.messaginghub.pooled.jms.JmsPoolSession` during the closing of a server side session. This is problematic, because I can't simply wrap a try catch around it and make it work. `jms-client-compliance.md` does indeed state that server side sessions are not supported. 

The asynchronous variant not working seems to have something to do with `setMessageListener` not actually doing anything. It doesn't sent a response back, so a timeout is triggered within the framework. I've tried to implement this method myself, but I my attempt was sadly unsucesfull.

**Comment by tommy2d** [comment]
@thomaspj10 I think this means that using RMQ through JMS is simply not viable right now. I think moving towards a native RMQ Facade/Browser/Listener/Sender seem inevitable to me.

**Comment by thomaspj10** [comment]
We do seem to have decent RabbitMQ support, but there are limitations. I can add messages to the queue and read messages from the queue using the following setup:

You do not have to modify the rabbitmq-jms-client for this.
- `ampq-client-5.23.0`
- `rabbitmq-jms-3.4.0`

`rabbitmq-plugins enable rabbitmq_jms_topic_exchange` is executed in a sh script in the Dockerfile entrypoint.

synchronous=true, is not possible, because selectors are not implemented in the JMS client. The Frank!Framework heavily depends on this, so that's why this breaks.

docker-compose.yml:
```yml
services:
  frankframework:
    volumes:
        - "./resources:/opt/frank/resources/"
    environment:
      transactionmanager.narayana.jms.connection.maxPoolSize: 1
    image: private.docker.nexus.frankframework.org/frankframework:9.0.0-SNAPSHOT
    ports:
      - "80:8080"
    
  rabbitmq:
    image: myrabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"

```

resources.yml:
```yml
jdbc:
  - name: "h2"
    type: "org.h2.jdbcx.JdbcDataSource"
    url: "jdbc:h2:mem:ibis4test;NON_KEYWORDS=VALUE;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;TRACE_LEVEL_FILE=0;"
jms:
  - name: "rabbitmq"
    type: "com.rabbitmq.jms.admin.RMQConnectionFactory"
    url: "amqp://host.docker.internal:5672/"
    properties:
      virtualHost: "/"
      host: "host.docker.internal"
      username: "guest"
      password: "guest"
```

Configuration.xml:
```xml
<Configuration name="Config">
	<JmsRealms>
		<jmsRealm realmName="jms" queueConnectionFactoryName="jms/rabbitmq" topicConnectionFactoryName="jms/rabbitmq"/>
	</JmsRealms>

    <Adapter name="Adapter">
        <Receiver name="ApiReceiver">
            <ApiListener
                name="ApiReceiverListener"
                uriPattern="test"
            />
        </Receiver>
        <Pipeline>
            <SenderPipe name="event-payload-sender">
   
                <JmsSender synchronous="false" jmsRealm="jms" deliveryMode="PERSISTENT" messageClass="TEXT" lookupDestination="false" destinationParam="destination" destinationType="QUEUE">

                    <Param name="destination" value="nameOfTheQueue" />
                </JmsSender>
            </SenderPipe>
        </Pipeline>
    </Adapter>

    <Adapter name="Reader">
        <Receiver name="receiver">
            <JmsListener name="jmsListener" destinationName="nameOfTheQueue" jmsRealm="jms" destinationType="QUEUE">

            </JmsListener>
        </Receiver>
        <Pipeline>
            <EchoPipe name="hello">
            </EchoPipe>
        </Pipeline>
    </Adapter>
</Configuration>
```

Hope this is enough for you to use RabbitMQ :)
